# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e1f7b136fced6a15f3683c15f3c32505bef4becbe7ceec29505f4e5ce6ffdaee40071d840ce6587718fe0a3a761198f1158991475423084c04cf90d2c34099ba

test:
  secret_key_base: 06e2876e6ceb8c2c4118a57293c75d756294aee2b350c6809fa07b072b93c3a883761eded03b06f7be744e3172f2e64e176a71fe907f11cac55da6cd3169fd62

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
